### ISSUE TITLE
add a function to allow rotating entire canvas

### ISSUE THREAD

**Issue by tuanway** [Servoy/svycanvas#3]

**Comment by tuanway** [comment]
https://github.com/fabricjs/fabric.js/issues/2382

**Comment by tuanway** [comment]
added a new api in latest commit

**Comment by dooley-cli** [comment]
Couple of issues:

1. Canvas loses rotation once you change the zoom level
2. If you have created a new object and it is still active and then rotate then the active object does not rotate.

**Comment by pdfitdave** [comment]
may i know what new api is added. I badly need to have this canvas rotation feature. Thank you

**Comment by jcompagner** [comment]
i do see a property rotate:

https://github.com/Servoy/svycanvas/blob/master/svycanvas/Canvas/Canvas.spec#L112
